	<footer id="page-footer">
		<p>Pets are awesome. While many people have kept many different species of animals in captivity over the course of human history, only a relative few have been kept long enough to be considered domesticated. Other types of animals, notably monkeys, have never been domesticated but are still commonly sold and kept as pets. There are also inanimate objects that have been kept as "pets", either as a form of game, or humorously (e.g. the pet rock or Chia pet).</p>
		<p>All content here borrowed from Wikipedia. We promise to put it back.</p>
	</footer>

